version: "2"
linters:
  default: all
  disable:
    - depguard
    - dupl
    - dupword
    - err113
    - exhaustruct
    - forbidigo
    - funlen
    - gocognit
    - gocritic
    - gocyclo
    - godot
    - godox
    - ireturn
    - lll
    - musttag
    - nestif
    - nlreturn
    - revive
    - tagalign
    - tagliatelle
    - testpackage
    - unparam
    - varnamelen
    - wrapcheck
    - wsl
    - noinlineerr
    - nonamedreturns
  settings:
    cyclop:
      max-complexity: 12
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
